steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=deploy/Dockerfile.v2
      - --tag=${_REPOSITORY}/agent-os:${_RELEASE_ID}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=deploy/Dockerfile.migrations-v2
      - --tag=${_REPOSITORY}/migrations:${_RELEASE_ID}
      - .
  - name: gcr.io/cloud-builders/docker
    args: [push, "${_REPOSITORY}/agent-os:${_RELEASE_ID}"]
  - name: gcr.io/cloud-builders/docker
    args: [push, "${_REPOSITORY}/migrations:${_RELEASE_ID}"]

images:
  - ${_REPOSITORY}/agent-os:${_RELEASE_ID}
  - ${_REPOSITORY}/migrations:${_RELEASE_ID}

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: ${_BUILD_SERVICE_ACCOUNT}

substitutions:
  _REPOSITORY: required
  _RELEASE_ID: required
  _BUILD_SERVICE_ACCOUNT: required
